namespace OpenVehicle.LibNet.Logging
{
    using System;


    /// <summary>
    ///     The log level.
    /// </summary>
    internal enum LogLevel
    {
        Trace,
        Debug,
        Info,
        Warn,
        Error,
        Fatal
    }


    /// <summary>
    ///     Simple interface that represent a logger.
    /// </summary>
    internal interface ILog
    {
        /// <summary>
        ///     Log a message the specified log level.
        /// </summary>
        /// <param name="logLevel">The log level.</param>
        /// <param name="messageFunc">The message function.</param>
        /// <param name="exception">An optional exception.</param>
        /// <param name="formatParameters">Optional format parameters for the message generated by the messagefunc. </param>
        /// <returns>true if the message was logged. Otherwise false.</returns>
        /// <remarks>
        ///     Note to implementers: the message func should not be called if the loglevel is not enabled
        ///     so as not to incur performance penalties.
        ///     To check IsEnabled call Log with only LogLevel and check the return value, no event will be written.
        /// </remarks>
        bool Log(LogLevel logLevel, Func<string> messageFunc, Exception exception = null,
            params object[] formatParameters);
    }


    static class LogExtensions
    {
        internal static readonly object[] EmptyParams = new object[0];

        public static bool IsDebugEnabled(this ILog logger)
        {
            return (logger!=null) ? logger.Log(LogLevel.Debug, null, null, EmptyParams) : false;
        }

        public static bool IsErrorEnabled(this ILog logger)
        {
            return (logger!=null) ? logger.Log(LogLevel.Error, null, null, EmptyParams) : false;
        }

        public static bool IsFatalEnabled(this ILog logger)
        {
            return (logger!=null) ? logger.Log(LogLevel.Fatal, null, null, EmptyParams) : false;
        }

        public static bool IsInfoEnabled(this ILog logger)
        {
            return (logger!=null) ? logger.Log(LogLevel.Info, null, null, EmptyParams) : false;
        }

        public static bool IsTraceEnabled(this ILog logger)
        {
            return (logger!=null) ? logger.Log(LogLevel.Trace, null, null, EmptyParams) : false;
        }

        public static bool IsWarnEnabled(this ILog logger)
        {
            return (logger!=null) ? logger.Log(LogLevel.Warn, null, null, EmptyParams) : false;
        }

        public static void Debug(this ILog logger, Func<string> messageFunc)
        {
            if (logger.IsDebugEnabled())
                logger.Log(LogLevel.Debug, WrapLogInternal(messageFunc), null, EmptyParams);
        }

        public static void Debug(this ILog logger, string message)
        {
            if (logger.IsDebugEnabled())
                logger.Log(LogLevel.Debug, message.AsFunc(), null, EmptyParams);
        }

        public static void Debug(this ILog logger, string message, params object[] args)
        {
            if (logger.IsDebugEnabled())
                logger.DebugFormat(message, args);
        }

        public static void Debug(this ILog logger, string message, object arg0)
        {
            if (logger.IsDebugEnabled())
                logger.DebugFormat(message, arg0);
        }

        public static void Debug(this ILog logger, string message, object arg0, object arg1)
        {
            if (logger.IsDebugEnabled())
                logger.DebugFormat(message, arg0, arg1);
        }

        public static void Debug(this ILog logger, string message, object arg0, object arg1, object arg2)
        {
            if (logger.IsDebugEnabled())
                logger.DebugFormat(message, arg0, arg1, arg2);
        }

        public static void Debug(this ILog logger, Exception exception, string message, params object[] args)
        {
            if (logger.IsDebugEnabled())
                logger.DebugException(message, exception, args);
        }

        public static void Debug(this ILog logger, Exception exception, string message, object arg0)
        {
            if (logger.IsDebugEnabled())
                logger.DebugException(message, exception, arg0);
        }

        public static void DebugFormat(this ILog logger, string message, params object[] args)
        {
            if (logger.IsDebugEnabled())
                logger.LogFormat(LogLevel.Debug, message, args);
        }

        public static void DebugFormat(this ILog logger, string message, object arg0)
        {
            if (logger.IsDebugEnabled())
                logger.LogFormat(LogLevel.Debug, message, arg0);
        }

        public static void DebugFormat(this ILog logger, string message, object arg0, object arg1)
        {
            if (logger.IsDebugEnabled())
                logger.LogFormat(LogLevel.Debug, message, arg0, arg1);
        }

        public static void DebugFormat(this ILog logger, string message, object arg0, object arg1, object arg2)
        {
            if (logger.IsDebugEnabled())
                logger.LogFormat(LogLevel.Debug, message, arg0, arg1, arg2);
        }

        public static void DebugException(this ILog logger, string message, Exception exception)
        {
            if (logger.IsDebugEnabled())
                logger.Log(LogLevel.Debug, message.AsFunc(), exception, EmptyParams);
        }

        public static void DebugException(this ILog logger, string message, Exception exception, object formatParam0)
        {
            if (logger.IsDebugEnabled())
                logger.Log(LogLevel.Debug, message.AsFunc(), exception, formatParam0);
        }

        public static void DebugException(this ILog logger, string message, Exception exception, object formatParam0,
            object formatParam1)
        {
            if (logger.IsDebugEnabled())
                logger.Log(LogLevel.Debug, message.AsFunc(), exception, formatParam0, formatParam1);
        }

        public static void DebugException(this ILog logger, string message, Exception exception, object formatParam0,
            object formatParam1, object formatParam2)
        {
            if (logger.IsDebugEnabled())
                logger.Log(LogLevel.Debug, message.AsFunc(), exception, formatParam0, formatParam1, formatParam2);
        }

        public static void DebugException(this ILog logger, string message, Exception exception,
            params object[] formatParams)
        {
            if (logger.IsDebugEnabled())
                logger.Log(LogLevel.Debug, message.AsFunc(), exception, formatParams);
        }

        public static void Error(this ILog logger, Func<string> messageFunc)
        {
            if (logger.IsErrorEnabled())
                logger.Log(LogLevel.Error, WrapLogInternal(messageFunc), null, EmptyParams);
        }

        public static void Error(this ILog logger, string message)
        {
            if (logger.IsErrorEnabled())
                logger.Log(LogLevel.Error, message.AsFunc(), null, EmptyParams);
        }

        public static void Error(this ILog logger, string message, params object[] args)
        {
            if (logger.IsErrorEnabled())
                logger.ErrorFormat(message, args);
        }

        public static void Error(this ILog logger, Exception exception, string message, params object[] args)
        {
            if (logger.IsErrorEnabled())
                logger.ErrorException(message, exception, args);
        }

        public static void ErrorFormat(this ILog logger, string message, params object[] args)
        {
            if (logger.IsErrorEnabled())
                logger.LogFormat(LogLevel.Error, message, args);
        }

        public static void ErrorException(this ILog logger, string message, Exception exception,
            params object[] formatParams)
        {
            if (logger.IsErrorEnabled())
                logger.Log(LogLevel.Error, message.AsFunc(), exception, formatParams);
        }

        public static void Fatal(this ILog logger, Func<string> messageFunc)
        {
            if (logger.IsFatalEnabled())
                logger.Log(LogLevel.Fatal, WrapLogInternal(messageFunc), null, EmptyParams);
        }

        public static void Fatal(this ILog logger, string message)
        {
            if (logger.IsFatalEnabled())
                logger.Log(LogLevel.Fatal, message.AsFunc(), null, EmptyParams);
        }

        public static void Fatal(this ILog logger, string message, params object[] args)
        {
            if (logger.IsFatalEnabled())
                logger.FatalFormat(message, args);
        }

        public static void Fatal(this ILog logger, Exception exception, string message, params object[] args)
        {
            if (logger.IsFatalEnabled())
                logger.FatalException(message, exception, args);
        }

        public static void FatalFormat(this ILog logger, string message, params object[] args)
        {
            if (logger.IsFatalEnabled())
                logger.LogFormat(LogLevel.Fatal, message, args);
        }

        public static void FatalException(this ILog logger, string message, Exception exception,
            params object[] formatParams)
        {
            if (logger.IsFatalEnabled())
                logger.Log(LogLevel.Fatal, message.AsFunc(), exception, formatParams);
        }

        public static void Info(this ILog logger, Func<string> messageFunc)
        {
            if (logger.IsInfoEnabled())
                logger.Log(LogLevel.Info, WrapLogInternal(messageFunc), null, EmptyParams);
        }

        public static void Info(this ILog logger, string message)
        {
            if (logger.IsInfoEnabled())
                logger.Log(LogLevel.Info, message.AsFunc(), null, EmptyParams);
        }

        public static void Info(this ILog logger, string message, params object[] args)
        {
            if (logger.IsInfoEnabled())
                logger.InfoFormat(message, args);
        }

        public static void Info(this ILog logger, string message, object arg0)
        {
            if (logger.IsInfoEnabled())
                logger.InfoFormat(message, arg0);
        }

        public static void Info(this ILog logger, string message, object arg0, object arg1)
        {
            if (logger.IsInfoEnabled())
                logger.InfoFormat(message, arg0, arg1);
        }

        public static void Info(this ILog logger, string message, object arg0, object arg1, object arg2)
        {
            if (logger.IsInfoEnabled())
                logger.InfoFormat(message, arg0, arg1, arg2);
        }

        public static void Info(this ILog logger, Exception exception, string message, params object[] args)
        {
            if (logger.IsInfoEnabled())
                logger.InfoException(message, exception, args);
        }

        public static void Info(this ILog logger, Exception exception, string message, object arg0)
        {
            if (logger.IsInfoEnabled())
                logger.InfoException(message, exception, arg0);
        }

        public static void Info(this ILog logger, Exception exception, string message, object arg0, object arg1)
        {
            if (logger.IsInfoEnabled())
                logger.InfoException(message, exception, arg0, arg1);
        }

        public static void Info(this ILog logger, Exception exception, string message, object arg0, object arg1,
            object arg2)
        {
            if (logger.IsInfoEnabled())
                logger.InfoException(message, exception, arg0, arg1, arg2);
        }

        public static void InfoFormat(this ILog logger, string message, params object[] args)
        {
            if (logger.IsInfoEnabled())
                logger.LogFormat(LogLevel.Info, message, args);
        }

        public static void InfoFormat(this ILog logger, string message, object arg0)
        {
            if (logger.IsInfoEnabled())
                logger.LogFormat(LogLevel.Info, message, arg0);
        }

        public static void InfoFormat(this ILog logger, string message, object arg0, object arg1)
        {
            if (logger.IsInfoEnabled())
                logger.LogFormat(LogLevel.Info, message, arg0, arg1);
        }

        public static void InfoFormat(this ILog logger, string message, object arg0, object arg1, object arg2)
        {
            if (logger.IsInfoEnabled())
                logger.LogFormat(LogLevel.Info, message, arg0, arg1, arg2);
        }

        public static void InfoException(this ILog logger, string message, Exception exception,
            params object[] formatParams)
        {
            if (logger.IsInfoEnabled())
                logger.Log(LogLevel.Info, message.AsFunc(), exception, formatParams);
        }

        public static void Trace(this ILog logger, Func<string> messageFunc)
        {
            if (logger.IsTraceEnabled())
                logger.Log(LogLevel.Trace, WrapLogInternal(messageFunc), null, EmptyParams);
        }

        public static void Trace(this ILog logger, string message)
        {
            if (logger.IsTraceEnabled())
                logger.Log(LogLevel.Trace, message.AsFunc(), null, EmptyParams);
        }

        public static void Trace(this ILog logger, string message, params object[] args)
        {
            if (logger.IsTraceEnabled())
                logger.TraceFormat(message, args);
        }

        public static void Trace(this ILog logger, string message, object arg0)
        {
            if (logger.IsTraceEnabled())
                logger.TraceFormat(message, arg0);
        }

        public static void Trace(this ILog logger, string message, object arg0, object arg1)
        {
            if (logger.IsTraceEnabled())
                logger.TraceFormat(message, arg0, arg1);
        }

        public static void Trace(this ILog logger, string message, object arg0, object arg1, object arg2)
        {
            if (logger.IsTraceEnabled())
                logger.TraceFormat(message, arg0, arg1, arg2);
        }

        public static void Trace(this ILog logger, Exception exception, string message, params object[] args)
        {
            if (logger.IsTraceEnabled())
                logger.TraceException(message, exception, args);
        }

        public static void Trace(this ILog logger, Exception exception, string message, object arg0)
        {
            if (logger.IsTraceEnabled())
                logger.TraceException(message, exception, arg0);
        }

        public static void Trace(this ILog logger, Exception exception, string message, object arg0, object arg1)
        {
            if (logger.IsTraceEnabled())
                logger.TraceException(message, exception, arg0, arg1);
        }

        public static void Trace(this ILog logger, Exception exception, string message, object arg0, object arg1,
            object arg2)
        {
            if (logger.IsTraceEnabled())
                logger.TraceException(message, exception, arg0, arg1, arg2);
        }

        public static void TraceFormat(this ILog logger, string message, params object[] args)
        {
            if (logger.IsTraceEnabled())
                logger.LogFormat(LogLevel.Trace, message, args);
        }

        public static void TraceFormat(this ILog logger, string message, object arg0)
        {
            if (logger.IsTraceEnabled())
                logger.LogFormat(LogLevel.Trace, message, arg0);
        }

        public static void TraceFormat(this ILog logger, string message, object arg0, object arg1)
        {
            if (logger.IsTraceEnabled())
                logger.LogFormat(LogLevel.Trace, message, arg0, arg1);
        }

        public static void TraceFormat(this ILog logger, string message, object arg0, object arg1, object arg2)
        {
            if (logger.IsTraceEnabled())
                logger.LogFormat(LogLevel.Trace, message, arg0, arg1, arg2);
        }

        public static void TraceException(this ILog logger, string message, Exception exception,
            params object[] formatParams)
        {
            if (logger.IsTraceEnabled())
                logger.Log(LogLevel.Trace, message.AsFunc(), exception, formatParams);
        }

        public static void TraceException(this ILog logger, string message, Exception exception, object formatParam0)
        {
            if (logger.IsTraceEnabled())
                logger.Log(LogLevel.Trace, message.AsFunc(), exception, formatParam0);
        }

        public static void TraceException(this ILog logger, string message, Exception exception, object formatParam0,
            object formatParam1)
        {
            if (logger.IsTraceEnabled())
                logger.Log(LogLevel.Trace, message.AsFunc(), exception, formatParam0, formatParam1);
        }

        public static void TraceException(this ILog logger, string message, Exception exception, object formatParam0,
            object formatParam1, object formatParam2)
        {
            if (logger.IsTraceEnabled())
                logger.Log(LogLevel.Trace, message.AsFunc(), exception, formatParam0, formatParam1, formatParam2);
        }

        public static void Warn(this ILog logger, Func<string> messageFunc)
        {
            if (logger.IsWarnEnabled())
                logger.Log(LogLevel.Warn, WrapLogInternal(messageFunc), null, EmptyParams);
        }

        public static void Warn(this ILog logger, string message)
        {
            if (logger.IsWarnEnabled())
                logger.Log(LogLevel.Warn, message.AsFunc(), null, EmptyParams);
        }

        public static void Warn(this ILog logger, string message, params object[] args)
        {
            if (logger.IsWarnEnabled())
                logger.WarnFormat(message, args);
        }

        public static void Warn(this ILog logger, Exception exception, string message, params object[] args)
        {
            if (logger.IsWarnEnabled())
                logger.WarnException(message, exception, args);
        }

        public static void WarnFormat(this ILog logger, string message, params object[] args)
        {
            if (logger.IsWarnEnabled())
                logger.LogFormat(LogLevel.Warn, message, args);
        }

        public static void WarnException(this ILog logger, string message, Exception exception,
            params object[] formatParams)
        {
            if (logger.IsWarnEnabled())
                logger.Log(LogLevel.Warn, message.AsFunc(), exception, formatParams);
        }

        private static void LogFormat(this ILog logger, LogLevel logLevel, string message, params object[] args)
        {
            if (logger != null)
                logger.Log(logLevel, message.AsFunc(), null, args);
        }

        // Avoid the closure allocation, see https://gist.github.com/AArnott/d285feef75c18f6ecd2b
        private static Func<T> AsFunc<T>(this T value) where T : class
        {
            return value.Return;
        }

        private static T Return<T>(this T value)
        {
            return value;
        }

        /*
        // Allow passing callsite-logger-type to LogProviderBase using messageFunc
        internal static Func<string> WrapLogSafeInternal(LoggerExecutionWrapper logger, Func<string> messageFunc)
        {
            string WrappedMessageFunc()
            {
                try
                {
                    return messageFunc();
                }
                catch (Exception ex)
                {
                    logger.WrappedLogger(LogLevel.Error, () => LoggerExecutionWrapper.FailedToGenerateLogMessage, ex,
                        EmptyParams);
                }

                return null;
            }

            return WrappedMessageFunc;
        }
        */

        // Allow passing callsite-logger-type to LogProviderBase using messageFunc
        private static Func<string> WrapLogInternal(Func<string> messageFunc)
        {
            string WrappedMessageFunc()
            {
                return messageFunc();
            }

            return WrappedMessageFunc;
        }
        
    }
}
